% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\title{Exploring the BRFSS data}
\author{}
\date{\vspace{-2.5em}}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Exploring the BRFSS data},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\begin{document}
\maketitle

\hypertarget{setup}{%
\subsection{Setup}\label{setup}}

\hypertarget{load-packages}{%
\subsubsection{Load packages}\label{load-packages}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\hypertarget{load-data}{%
\subsubsection{Load data}\label{load-data}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{load}\NormalTok{(}\StringTok{"brfss2013.Rdata"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{part-1-data}{%
\subsection{Part 1: Data}\label{part-1-data}}

The information in the sample were collected though a system of
health-related telephone surveys that gathered state data about U.S.
residents regarding their health-related risk behaviors, chronic health
conditions, and use of preventive services.The survey was carried out in
all 50 states in US as well as the District of Columbia and three U.S.
territories. Since 2011, BRFSS conducts both landline telephone- and
cellular telephone-based surveys. In conducting the BRFSS landline
telephone survey, interviewers collect data from a randomly selected
adult in a household. In conducting the cellular telephone version of
the BRFSS questionnaire, interviewers collect data from an adult who
participates by using a cellular telephone and resides in a private
residence or college housing.

The data were collected through a random sample of adults in US and the
implication of this data collection is to gather uniform, state-specific
data on preventive health practices and risk behaviors that are linked
to chronic diseases, injuries, and preventable infectious diseases that
affect the adult population.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{part-2-research-questions}{%
\subsection{Part 2: Research
questions}\label{part-2-research-questions}}

\textbf{Research quesion 1:}

It is well known that people with Arthritis feel lots of pain and in
many cases it can turn their lives into a nightmare because they cannot
do basic things such as walking, bathing, going to a market and so on.
For this reason I will check the impact of this disease on people's
lives.

\textbf{Research quesion 2:}

Diabetes is one of the main responsible for blindness caused by a
disease among the adult population around the world and thinking about
that I decided to compare and analyse if there is any relation between
the illness and blindness in this sample from USA. Moreover, I will
check using a variable from the dataset if people who have diabetes and
are blind were told about this relation.

\textbf{Research quesion 3:}

In the last question I will analyse if there is any relation among sleep
disorders, depression and hypertension because according to (Batal et
al., 2011) these disorders are a risk factor for both high blood
pressure and depression.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{part-3-exploratory-data-analysis}{%
\subsection{Part 3: Exploratory data
analysis}\label{part-3-exploratory-data-analysis}}

\textbf{Research quesion 1:}

Firstly I organized the data selecting the variables I wanted to work
with (havarth3 ,diffwalk, diffdres and diffalon) in the object named
``artrite'' and after that I turned the factor data (yes/no) into
numeric ones in order to get some useful insights for my plots.

Just to clarify the variables mentioned above:

\begin{itemize}
\tightlist
\item
  havarth3: People Told Have Arthritis;
\item
  diffwalk: Difficulty Walking Or Climbing Stairs;
\item
  diffdres: Difficulty Dressing Or Bathing;
\item
  diffalon: Difficulty Doing Errands Alone.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{artrite }\OtherTok{\textless{}{-}}\NormalTok{ brfss2013 }\SpecialCharTok{\%\textgreater{}\%} 
   \FunctionTok{select}\NormalTok{(havarth3 ,diffwalk, diffdres, diffalon) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{diffwalk\_bin =} \FunctionTok{recode}\NormalTok{(diffwalk,}
                            \StringTok{"Yes"} \OtherTok{=} \DecValTok{1}\NormalTok{,}
                            \StringTok{"No"} \OtherTok{=} \DecValTok{0}\NormalTok{),}
         \AttributeTok{diffdress\_bin =} \FunctionTok{recode}\NormalTok{(diffdres,}
                            \StringTok{"Yes"} \OtherTok{=} \DecValTok{1}\NormalTok{,}
                            \StringTok{"No"} \OtherTok{=} \DecValTok{0}\NormalTok{),}
         \AttributeTok{diffalon\_bin =} \FunctionTok{recode}\NormalTok{(diffalon,}
                            \StringTok{"Yes"} \OtherTok{=} \DecValTok{1}\NormalTok{,}
                            \StringTok{"No"} \OtherTok{=} \DecValTok{0}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(}\FunctionTok{everything}\NormalTok{(), }\SpecialCharTok{{-}}\NormalTok{(}\DecValTok{2}\SpecialCharTok{:}\DecValTok{4}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Secondly I separated the object, that contains 491.775 parameters, into
two where the first one is related to people without arthritis and the
another one concerns people with. I did that because I wanted to show
the huge difference that exists between these two groups when it comes
to problems caused by this disease. Once I got the data I was looking
for I created two different plots regarding people with and without
arthritis.

First of all, I created a new object named ``noarth'' to separate people
without the illness.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{noarth }\OtherTok{\textless{}{-}}\NormalTok{ artrite }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(havarth3 }\SpecialCharTok{==} \StringTok{"No"}\NormalTok{)}

\NormalTok{noarth }\OtherTok{\textless{}{-}}\NormalTok{ noarth }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{mutate}\NormalTok{(}\AttributeTok{total =} \FunctionTok{rowSums}\NormalTok{(noarth[ ,}\DecValTok{2}\SpecialCharTok{:}\DecValTok{4}\NormalTok{], }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

I found there are 323.653 people out of 491.775 in this condition (no
arthritis) which represents 65.81\% of total.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(artrite), }\StringTok{" Total Sample"}\NormalTok{, }\AttributeTok{sep =} \StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "491775 Total Sample"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(noarth), }\StringTok{" People without Arthritis "}\NormalTok{, }\AttributeTok{sep =} \StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "323653 People without Arthritis "
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\StringTok{"Percentage "}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(noarth)}\SpecialCharTok{*}\DecValTok{100}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(artrite), }\AttributeTok{digits =} \DecValTok{2}\NormalTok{), }\StringTok{"\%"}\NormalTok{, }\AttributeTok{sep=} \StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Percentage 65.81%"
\end{verbatim}

And I made a plot using ggplot showing the amount of problems people
without arthritis said they have. Note that these 3 problems are the
ones I mentioned on the description of this first case study:

\begin{itemize}
\tightlist
\item
  Difficulty Walking Or Climbing Stairs;
\item
  Difficulty Dressing Or Bathing;
\item
  Difficulty Doing Errands Alone.
\end{itemize}

If a person said he or she had some issue to walk or wear a t-shirt for
example, they got 1 in the respective variable and 0 in case of a
negative feedback. In other words, I changed the ``yes/no'' answers to
1/0 where 1 stands for ``yes'' and 0 for ``no'' due to it is easier to
work and manipulate data like that.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(noarth) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ total), }\AttributeTok{fill =} \StringTok{"forest green"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Amount of Problems"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Sample Size"}\NormalTok{,}
       \AttributeTok{title =} \StringTok{"Sample of People Without Arthritis"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{FinalProject-_Notebook_files/figure-latex/unnamed-chunk-4-1.pdf}

As we can see, the majority of people without the disease have no
problems (0) that are commonly related to it. The result was very
satisfactory because we were expecting for numbers like that. Below we
have a summary of the finds:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{noarth\_summary }\OtherTok{\textless{}{-}}\NormalTok{ noarth }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{count}\NormalTok{(total)}

\NormalTok{noarth\_summary }\OtherTok{\textless{}{-}}\NormalTok{ noarth\_summary }\SpecialCharTok{\%\textgreater{}\%}   
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{percent =} \FunctionTok{round}\NormalTok{(noarth\_summary}\SpecialCharTok{$}\NormalTok{n}\SpecialCharTok{*}\DecValTok{100}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(noarth), }\AttributeTok{digits =} \DecValTok{2}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} 
         \FunctionTok{rename}\NormalTok{(}\StringTok{"n\_of\_problems"} \OtherTok{=}\NormalTok{ total,}
                \StringTok{"total"} \OtherTok{=}\NormalTok{ n)}

\FunctionTok{print}\NormalTok{(noarth\_summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   n_of_problems  total percent
## 1             0 292805   90.47
## 2             1  21354    6.60
## 3             2   6352    1.96
## 4             3   3142    0.97
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(noarth\_summary) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ n\_of\_problems, }\AttributeTok{y =}\NormalTok{ total), }\AttributeTok{fill =} \StringTok{" forest green"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ n\_of\_problems, }\AttributeTok{y =}\NormalTok{ total, }\AttributeTok{label =}\NormalTok{ percent), }\AttributeTok{vjust =} \SpecialCharTok{{-}}\FloatTok{0.3}\NormalTok{, }\AttributeTok{size =} \FloatTok{3.5}\NormalTok{, ) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Amount of Problems (\%)"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Sample Size"}\NormalTok{,}
       \AttributeTok{title =} \StringTok{"Sample of People Without Arthritis"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_classic}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{FinalProject-_Notebook_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{itemize}
\tightlist
\item
  90.47\% of the people without arthritis have no pain or any difficulty
  to accomplish daily basic functions;
\item
  Less than 1\% said they were facing all the 3 problems, which is a
  very low number.
\end{itemize}

Now I got the data for people with arthritis. Let's see the
outcomes\ldots{}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arth }\OtherTok{\textless{}{-}}\NormalTok{ artrite }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(havarth3 }\SpecialCharTok{==} \StringTok{"Yes"}\NormalTok{) }

\NormalTok{arth }\OtherTok{\textless{}{-}}\NormalTok{ arth }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{mutate}\NormalTok{(}\AttributeTok{total =} \FunctionTok{rowSums}\NormalTok{(arth[ ,}\DecValTok{2}\SpecialCharTok{:}\DecValTok{4}\NormalTok{], }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

As expected due to the previous outcomes, there are 165.152 people out
of 491.775 with arthritis which represent 33.58\% of total.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(artrite), }\StringTok{" Total Sample"}\NormalTok{, }\AttributeTok{sep =} \StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "491775 Total Sample"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(arth), }\StringTok{" People with Arthritis"}\NormalTok{, }\AttributeTok{sep =} \StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "165152 People with Arthritis"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\StringTok{"Percentage "}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(arth)}\SpecialCharTok{*}\DecValTok{100}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(artrite), }\AttributeTok{digits =} \DecValTok{2}\NormalTok{), }\StringTok{"\%"}\NormalTok{,}\AttributeTok{sep =} \StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Percentage 33.58%"
\end{verbatim}

The chart shows a completely different pattern in comparison to the
first one. In this one we can see there is a huge amount of people with
daily problems that are commonly related to arthritis.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{ (arth) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ total), }\AttributeTok{fill =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{( }\AttributeTok{x =} \StringTok{"Amount of Problems"}\NormalTok{,}
        \AttributeTok{y =} \StringTok{"Sample Size"}\NormalTok{,}
        \AttributeTok{title =} \StringTok{"Sample of People With Arthritis"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{FinalProject-_Notebook_files/figure-latex/unnamed-chunk-9-1.pdf}

This outcome was not surprising because people with the illness usually
have some difficulty to do some daily activities, even the basic ones
like walking or wearing a shirt or a pant. You can see below a table
showing all the results, including the respective percentage:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arth\_summary }\OtherTok{\textless{}{-}}\NormalTok{ arth }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{count}\NormalTok{(total)}

\NormalTok{arth\_summary }\OtherTok{\textless{}{-}}\NormalTok{ arth\_summary }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{percent =} \FunctionTok{round}\NormalTok{(arth\_summary}\SpecialCharTok{$}\NormalTok{n}\SpecialCharTok{*}\DecValTok{100}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(arth), }\AttributeTok{digits =} \DecValTok{2}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} 
   \FunctionTok{rename}\NormalTok{(}\StringTok{"num\_of\_problems"} \OtherTok{=}\NormalTok{ total,}
                \StringTok{"total"} \OtherTok{=}\NormalTok{ n)}

\FunctionTok{print}\NormalTok{(arth\_summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   num_of_problems total percent
## 1               0 99085   60.00
## 2               1 39908   24.16
## 3               2 16355    9.90
## 4               3  9804    5.94
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(arth\_summary) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ num\_of\_problems, }\AttributeTok{y =}\NormalTok{ total), }\AttributeTok{fill =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{ num\_of\_problems, }\AttributeTok{y =}\NormalTok{ total, }\AttributeTok{label =}\NormalTok{ percent), }\AttributeTok{vjust =} \SpecialCharTok{{-}}\FloatTok{0.3}\NormalTok{, }\AttributeTok{size =} \FloatTok{3.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{( }\AttributeTok{x =} \StringTok{"Amount of Problems (\%)"}\NormalTok{,}
        \AttributeTok{y =} \StringTok{"Sample Size"}\NormalTok{,}
        \AttributeTok{title =} \StringTok{"Sample of People With Arthritis"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_classic}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{FinalProject-_Notebook_files/figure-latex/unnamed-chunk-11-1.pdf}

The amount of people who find some activities very difficult due to
joint pain increased significally as expected because people on this
sample have arthritis. We saw in the first graph that more than 90\% of
people without the disease had no issues with pain, while in this one
the percentage drops to 60\%. Although we can see there is a strong
relation between arthritis and the problems mentioned in this case
study, we cannot say there is a causation due to it is necessary to
analyse every single case to make sure these problems are not caused by
other factors.

\textbf{Research quesion 2:}

Firstly I organized the data again selecting the variables I wanted to
work with (diabete3, blind, diabeye) in the object named ``diabetes''
and after that I turned the factor data (yes/no) into numeric ones in
order to get some useful insights for my plots.

Just to clarify the variables mentioned above:

\begin{itemize}
\tightlist
\item
  diabete3: (Ever Told) You Have Diabetes;
\item
  blind: Blind Or Difficulty Seeing;
\item
  diabeye: Ever Told Diabetes Has Affected Eyes.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diabetes }\OtherTok{\textless{}{-}}\NormalTok{ brfss2013 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(diabete3, blind, diabeye) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{diabete3 =} \FunctionTok{recode}\NormalTok{(diabete3,}
                           \StringTok{"No, pre{-}diabetes or borderline diabetes"} \OtherTok{=} \StringTok{"No"}\NormalTok{,}
                           \StringTok{"Yes, but female told only during pregnancy"} \OtherTok{=} \StringTok{"Yes"}\NormalTok{),}
         \AttributeTok{blind\_bin =} \FunctionTok{recode}\NormalTok{(blind,}
                            \StringTok{"Yes"} \OtherTok{=} \DecValTok{1}\NormalTok{,}
                            \StringTok{"No"} \OtherTok{=} \DecValTok{0}\NormalTok{),}
         \AttributeTok{dbeye\_bin =} \FunctionTok{recode}\NormalTok{(diabeye,}
                            \StringTok{"Yes"} \OtherTok{=} \DecValTok{1}\NormalTok{,}
                            \StringTok{"No"} \OtherTok{=} \DecValTok{0}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(}\FunctionTok{everything}\NormalTok{(), }\SpecialCharTok{{-}}\NormalTok{(}\DecValTok{2}\SpecialCharTok{:}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

At this time I separated and selected only the data about people with
diabetes because the rest of the it did not present relevant information
for what I am interested in.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diab }\OtherTok{\textless{}{-}}\NormalTok{ diabetes }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(diabete3 }\SpecialCharTok{==} \StringTok{"Yes"}\NormalTok{) }

\NormalTok{diab }\OtherTok{\textless{}{-}}\NormalTok{ diab }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{total =} \FunctionTok{rowSums}\NormalTok{(diab[ ,}\DecValTok{2}\SpecialCharTok{:}\DecValTok{3}\NormalTok{], }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)) }
\end{Highlighting}
\end{Shaded}

We can see below only 66.965 people out of 491.775 said they have
diabetes and it represents 13.62\% of the total sample.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(diabetes), }\StringTok{" Total Sample"}\NormalTok{, }\AttributeTok{sep =} \StringTok{""}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "491775 Total Sample"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(diab), }\StringTok{" Total of people with diabetes"}\NormalTok{, }\AttributeTok{sep =} \StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "66965 Total of people with diabetes"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\StringTok{"Percentage "}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(diab)}\SpecialCharTok{*}\DecValTok{100}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(diabetes), }\AttributeTok{digits =} \DecValTok{2}\NormalTok{), }\StringTok{"\%"}\NormalTok{, }\AttributeTok{sep =} \StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Percentage 13.62%"
\end{verbatim}

Visualization of the previous finds:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diabetes\_teste }\OtherTok{\textless{}{-}}\NormalTok{ diabetes }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{count}\NormalTok{(diabete3)}

\FunctionTok{ggplot}\NormalTok{(diabetes\_teste) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ diabete3, }\AttributeTok{y =}\NormalTok{ n, }\AttributeTok{fill =}\NormalTok{ diabete3)) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ diabete3, }\AttributeTok{y =}\NormalTok{ n, }\AttributeTok{label =}\NormalTok{ n), }\AttributeTok{vjust =} \SpecialCharTok{{-}}\FloatTok{0.5}\NormalTok{, }\AttributeTok{size =} \FloatTok{3.3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Diabetes Prevalence in the Sample"}\NormalTok{,}
      \AttributeTok{x =} \StringTok{"Diabetes"}\NormalTok{,}
      \AttributeTok{y =} \StringTok{"Sample Size"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{FinalProject-_Notebook_files/figure-latex/unnamed-chunk-15-1.pdf}

I used a different approach with this data because I want to know how
many people with diabetes are blind and how many of them were told this
illness could cause it. I created a new object named
``diabetes\_summary'' to get a better overview of my dataset.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diabetes\_summary }\OtherTok{\textless{}{-}}\NormalTok{ diab }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{count}\NormalTok{(blind\_bin, dbeye\_bin) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(blind\_bin }\SpecialCharTok{==} \DecValTok{1} \SpecialCharTok{|}\NormalTok{ dbeye\_bin }\SpecialCharTok{==} \DecValTok{1}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{rename}\NormalTok{(}\StringTok{"blindness"} \OtherTok{=}\NormalTok{ blind\_bin,}
        \StringTok{"awareness"} \OtherTok{=}\NormalTok{ dbeye\_bin,}
        \StringTok{"total"} \OtherTok{=}\NormalTok{ n) }
  

\FunctionTok{print}\NormalTok{(diabetes\_summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   blindness awareness total
## 1         0         1  4990
## 2         1         0  2358
## 3         1         1  1907
## 4         1        NA  3099
## 5        NA         1   150
\end{verbatim}

Looking at the table above it is possible to get some useful data which
suit some parameters and the results are interesting! Fo example, only
10.52\% of people who have diabetes were aware this disease is one of
the main causes of blindness among the adult population over the world.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{per\_awar }\OtherTok{\textless{}{-}}\NormalTok{ diab }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(diab}\SpecialCharTok{$}\NormalTok{dbeye\_bin }\SpecialCharTok{==} \DecValTok{1}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{count}\NormalTok{(dbeye\_bin)}

\NormalTok{per\_awar }\OtherTok{\textless{}{-}}\NormalTok{ per\_awar }\SpecialCharTok{\%\textgreater{}\%}  
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{per\_awr =} \FunctionTok{round}\NormalTok{(per\_awar}\SpecialCharTok{$}\NormalTok{n}\SpecialCharTok{*}\DecValTok{100}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(diab), }\AttributeTok{digits =} \DecValTok{2}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} 
         \FunctionTok{rename}\NormalTok{(}\StringTok{"awareness"} \OtherTok{=}\NormalTok{ dbeye\_bin,}
                \StringTok{"total"} \OtherTok{=}\NormalTok{ n,}
                \StringTok{"percentage"} \OtherTok{=}\NormalTok{ per\_awr) }
  

\FunctionTok{print}\NormalTok{(per\_awar)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   awareness total percentage
## 1         1  7047      10.52
\end{verbatim}

A quick summary to explain better the other results I got:

\begin{itemize}
\tightlist
\item
  There are 7.364 blind people out of 66.965 with diabetes (11\%);
\item
  5.457 blind individuals in 7.364 were not aware of the relation
  between diabetes and blindness (74.10\%);
\item
  2.85\% of the total of people with diabetes are blind and were told
  about the relation.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{blind\_awar }\OtherTok{\textless{}{-}}\NormalTok{ diabetes\_summary }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(blindness }\SpecialCharTok{==} \DecValTok{1} \SpecialCharTok{\&}\NormalTok{ awareness }\SpecialCharTok{==}\DecValTok{1}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}  
  \FunctionTok{count}\NormalTok{(total) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{blind\_awar\_per =} \FunctionTok{round}\NormalTok{(}\DecValTok{1907}\SpecialCharTok{*}\DecValTok{100}\SpecialCharTok{/}\DecValTok{7364}\NormalTok{, }\AttributeTok{digits =} \DecValTok{2}\NormalTok{)) }
  
  
\FunctionTok{print}\NormalTok{(blind\_awar)  }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   total n blind_awar_per
## 1  1907 1           25.9
\end{verbatim}

Now I finally have the result I was looking for this second question:

\begin{itemize}
\tightlist
\item
  Only 1.907 blind people with diabetes (25.90\%) knew about the
  relation and that's a very low number and it suggests it should be
  created an awareness campaign to let people know about the risks of
  getting blind because of diabetes.
\end{itemize}

Perhaps if people had more knowledge about that, many of them could have
avoided losing their vision. But again, we cannot confirm any causation
here as well.

\textbf{Research quesion 3:}

Firstly I selected and organized the variables I wanted to work with. In
this question I picked the following ones:

\begin{itemize}
\tightlist
\item
  sleptim1: How Much Time Do You Sleep;
\item
  addepev2: Ever Told You Had A Depressive Disorder;
\item
  bphigh4: Ever Told Blood Pressure High
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{insomnia1 }\OtherTok{\textless{}{-}}\NormalTok{ brfss2013 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(sleptim1, bphigh4, addepev2)}
\end{Highlighting}
\end{Shaded}

As we can see in the dataset above the ``sleptim1'' variable only gives
us how may hours an individual says he or she sleeps and for this reason
I need to clear this data because I want to work with information
regarding people with sleep disorders. People who sleep less than 6
hours a day are considered to have some sleep disorder (Pereira, 2021)
and I will use this fact to filter my data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{insomnia }\OtherTok{\textless{}{-}}\NormalTok{ brfss2013 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(sleptim1 }\SpecialCharTok{\textless{}=} \DecValTok{6}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(sleptim1, bphigh4, addepev2) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{rename}\NormalTok{(}\StringTok{"sleep\_hours"} \OtherTok{=}\NormalTok{ sleptim1,}
         \StringTok{"hypertension"} \OtherTok{=}\NormalTok{ bphigh4,}
         \StringTok{"depression"} \OtherTok{=}\NormalTok{ addepev2)}
\end{Highlighting}
\end{Shaded}

Amount of people according to their sleep hours:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{insomnia\_summary2 }\OtherTok{\textless{}{-}}\NormalTok{ insomnia }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{hypertension =} \FunctionTok{recode}\NormalTok{(hypertension,}
                               \StringTok{"Yes, but female told only during pregnancy"} \OtherTok{=} \StringTok{"Yes"}\NormalTok{,}
                               \StringTok{"Told borderline or pre{-}hypertensive"} \OtherTok{=} \StringTok{"Yes"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{count}\NormalTok{(sleep\_hours)}

\FunctionTok{print}\NormalTok{(insomnia\_summary2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   sleep_hours      n
## 1           0      1
## 2           1    228
## 3           2   1076
## 4           3   3496
## 5           4  14261
## 6           5  33436
## 7           6 106197
\end{verbatim}

A quick overview of my dataset:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(insomnia1), }\StringTok{" Total Sample"}\NormalTok{, }\AttributeTok{sep =} \StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "491775 Total Sample"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(insomnia), }\StringTok{" People with a Potential Sleep Disorder"}\NormalTok{, }\AttributeTok{sleep =} \StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "158695  People with a Potential Sleep Disorder "
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\StringTok{"Percentage "}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(insomnia)}\SpecialCharTok{*}\DecValTok{100}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(insomnia1), }\AttributeTok{digits =} \DecValTok{2}\NormalTok{), }\StringTok{"\%"}\NormalTok{, }\AttributeTok{sep =}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Percentage 32.27%"
\end{verbatim}

We can see 32.27\% of the people in the sample (158.695) can potentially
have some sleep disorders like insomnia, narcolepsy or sleep apnea.

Now I summarized my dataset to facilitate my data analysis. I will only
select people who suffers at least of one of both diseases mentioned in
this case study and will sum the amount of people according to their
sleep hours.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{insomnia\_summary1 }\OtherTok{\textless{}{-}}\NormalTok{ insomnia }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{hypertension =} \FunctionTok{recode}\NormalTok{(hypertension,}
                               \StringTok{"Yes, but female told only during pregnancy"} \OtherTok{=} \StringTok{"Yes"}\NormalTok{,}
                               \StringTok{"Told borderline or pre{-}hypertensive"} \OtherTok{=} \StringTok{"Yes"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(hypertension }\SpecialCharTok{==} \StringTok{"Yes"} \SpecialCharTok{|}\NormalTok{ depression }\SpecialCharTok{==} \StringTok{"Yes"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{count}\NormalTok{(sleep\_hours)}

\FunctionTok{print}\NormalTok{(insomnia\_summary1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   sleep_hours     n
## 1           0     1
## 2           1   155
## 3           2   819
## 4           3  2623
## 5           4  9842
## 6           5 20059
## 7           6 55532
\end{verbatim}

Looking at the dataset above I could find how many people who sleep less
than 6 hours suffer of either hypertension or depression, or even both.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\FunctionTok{sum}\NormalTok{(insomnia\_summary1}\SpecialCharTok{$}\NormalTok{n), }\StringTok{" People with depression or/and hypertension"}\NormalTok{, }\AttributeTok{sep =} \StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "89031 People with depression or/and hypertension"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\StringTok{"Percentage "}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{sum}\NormalTok{(insomnia\_summary1}\SpecialCharTok{$}\NormalTok{n)}\SpecialCharTok{*}\DecValTok{100}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(insomnia), }\AttributeTok{digits =} \DecValTok{2}\NormalTok{), }\StringTok{"\%"}\NormalTok{ ,}\AttributeTok{sep =} \StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Percentage 56.1%"
\end{verbatim}

The finds of this analysis are quite chocking because more than half of
the sample has a disease that is highly connected to a poor sleep habit.

Now I just need to merge the ``insomnia\_summary1'' dataframe into the
``insomnia\_summary2'' one to be able to create a proper plot about the
results I want to.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{completo }\OtherTok{\textless{}{-}} \FunctionTok{left\_join}\NormalTok{(insomnia\_summary1, insomnia\_summary2, }\AttributeTok{by =} \StringTok{"sleep\_hours"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{rename}\NormalTok{(}\StringTok{"tot\_hyp\_dep"} \OtherTok{=}\NormalTok{ n.x,}
         \StringTok{"total"} \OtherTok{=}\NormalTok{ n.y)}

\NormalTok{completo }\OtherTok{\textless{}{-}}\NormalTok{ completo }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{percent =} \FunctionTok{round}\NormalTok{(completo}\SpecialCharTok{$}\NormalTok{tot\_hyp\_dep}\SpecialCharTok{*}\DecValTok{100}\SpecialCharTok{/}\NormalTok{completo}\SpecialCharTok{$}\NormalTok{total))}


\FunctionTok{print}\NormalTok{(completo)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   sleep_hours tot_hyp_dep  total percent
## 1           0           1      1     100
## 2           1         155    228      68
## 3           2         819   1076      76
## 4           3        2623   3496      75
## 5           4        9842  14261      69
## 6           5       20059  33436      60
## 7           6       55532 106197      52
\end{verbatim}

Finally I can generate my chart about the possible relation among sleep
disorders and hypertension/depression

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(completo, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ sleep\_hours, }\AttributeTok{y =}\NormalTok{ total, }\AttributeTok{color =}\NormalTok{ tot\_hyp\_dep)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{size =} \FloatTok{0.8}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =}\NormalTok{ percent), }\AttributeTok{vjust =} \SpecialCharTok{{-}}\FloatTok{0.3}\NormalTok{, }\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{size =} \FloatTok{3.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{ (}\AttributeTok{title =} \StringTok{"Relation between hours of sleep and hypertension/depression (\%) "}\NormalTok{,}
        \AttributeTok{x =} \StringTok{"hours of sleep"}\NormalTok{,}
        \AttributeTok{y =} \StringTok{"total of people"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{FinalProject-_Notebook_files/figure-latex/unnamed-chunk-26-1.pdf}

As we can see, there is a considerable relation between poor sleep
habits to hypertension and depression. The less hours someone sleeps,
the more chance he or she has to get a disease associated to that taking
into consideration the people in our sample.

Once more, we cannot affirm there is a causation in our sample because
we need to get more detailed information about every single person who
took part in the survey.

According to the graph:

\begin{itemize}
\tightlist
\item
  68\% of people who sleep only 1 hour a day have at least one of both
  illnesses;
\item
  76\% of people who sleep only 2 hours a day have at least one of both
  illnesses;
\item
  75\% of people who sleep only 3 hours a day have at least one of both
  illnesses;
\item
  69\% of people who sleep only 4 hours a day have at least one of both
  illnesses;
\item
  60\% of people who sleep only 5 hours a day have at least one of both
  illnesses;
\item
  52\% of people who sleep only 6 hours a day have at least one of both
  illnesses.
\end{itemize}

PS. I am not taking into consideration the 100\% concerning 0 (no sleep)
because there was only one individual in the sample and it is not
statistically relevant. It is probably an outlier.

\end{document}
